# Generated by Django 3.1.1 on 2021-01-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cj1',
            new_name='English',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cj2',
            new_name='chinese',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cj3',
            new_name='mathematics',
        ),
    ]
